-- Core schema for HR Leave Management System

CREATE TABLE employees (
    employee_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_code         VARCHAR2(30) NOT NULL UNIQUE,
    full_name        VARCHAR2(120) NOT NULL,
    email            VARCHAR2(200) NOT NULL UNIQUE,
    manager_id       NUMBER,
    hire_date        DATE NOT NULL,
    is_active        CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_employees_is_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT fk_employees_manager FOREIGN KEY (manager_id)
        REFERENCES employees (employee_id)
);

CREATE TABLE leave_types (
    leave_type_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_code               VARCHAR2(30) NOT NULL UNIQUE,
    leave_name               VARCHAR2(80) NOT NULL,
    yearly_quota_days        NUMBER(6,2) NOT NULL,
    carry_forward_allowed    CHAR(1) DEFAULT 'N' NOT NULL,
    is_active                CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT chk_leave_types_carry_forward CHECK (carry_forward_allowed IN ('Y','N')),
    CONSTRAINT chk_leave_types_is_active CHECK (is_active IN ('Y','N')),
    CONSTRAINT chk_leave_types_quota CHECK (yearly_quota_days >= 0)
);

CREATE TABLE holiday_calendar (
    holiday_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date     DATE NOT NULL UNIQUE,
    holiday_name     VARCHAR2(120) NOT NULL,
    is_optional      CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT chk_holiday_optional CHECK (is_optional IN ('Y','N'))
);

CREATE TABLE leave_balances (
    balance_id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id             NUMBER NOT NULL,
    leave_type_id           NUMBER NOT NULL,
    balance_year            NUMBER(4) NOT NULL,
    opening_balance_days    NUMBER(6,2) DEFAULT 0 NOT NULL,
    accrued_days            NUMBER(6,2) DEFAULT 0 NOT NULL,
    used_days               NUMBER(6,2) DEFAULT 0 NOT NULL,
    adjusted_days           NUMBER(6,2) DEFAULT 0 NOT NULL,
    created_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_leave_balances_emp_type_year UNIQUE (employee_id, leave_type_id, balance_year),
    CONSTRAINT fk_leave_bal_emp FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT fk_leave_bal_type FOREIGN KEY (leave_type_id) REFERENCES leave_types (leave_type_id),
    CONSTRAINT chk_leave_balances_year CHECK (balance_year BETWEEN 2000 AND 2099)
);

CREATE TABLE leave_requests (
    request_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id           NUMBER NOT NULL,
    leave_type_id         NUMBER NOT NULL,
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    requested_days        NUMBER(6,2) NOT NULL,
    reason                VARCHAR2(500),
    status                VARCHAR2(30) DEFAULT 'PENDING_MANAGER' NOT NULL,
    submitted_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    decided_at            TIMESTAMP,
    cancel_reason         VARCHAR2(500),
    CONSTRAINT fk_leave_req_emp FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT fk_leave_req_type FOREIGN KEY (leave_type_id) REFERENCES leave_types (leave_type_id),
    CONSTRAINT chk_leave_req_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_leave_req_status CHECK (status IN (
        'PENDING_MANAGER',
        'PENDING_HR',
        'APPROVED',
        'REJECTED',
        'CANCELLED'
    ))
);

CREATE TABLE leave_approvals (
    approval_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id           NUMBER NOT NULL,
    approver_id          NUMBER NOT NULL,
    approval_level       NUMBER(2) NOT NULL,
    action_taken         VARCHAR2(30) NOT NULL,
    action_at            TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    comments             VARCHAR2(500),
    CONSTRAINT fk_leave_appr_req FOREIGN KEY (request_id) REFERENCES leave_requests (request_id),
    CONSTRAINT fk_leave_appr_user FOREIGN KEY (approver_id) REFERENCES employees (employee_id),
    CONSTRAINT chk_leave_appr_level CHECK (approval_level IN (1, 2)),
    CONSTRAINT chk_leave_appr_action CHECK (action_taken IN ('APPROVED','REJECTED'))
);

CREATE TABLE notification_queue (
    notification_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_emp_id     NUMBER NOT NULL,
    subject              VARCHAR2(200) NOT NULL,
    message_body         VARCHAR2(1000) NOT NULL,
    channel              VARCHAR2(20) DEFAULT 'EMAIL' NOT NULL,
    status               VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    sent_at              TIMESTAMP,
    CONSTRAINT fk_notif_emp FOREIGN KEY (recipient_emp_id) REFERENCES employees (employee_id),
    CONSTRAINT chk_notif_channel CHECK (channel IN ('EMAIL','INAPP')),
    CONSTRAINT chk_notif_status CHECK (status IN ('PENDING','SENT','FAILED'))
);

CREATE TABLE app_error_log (
    error_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name          VARCHAR2(100) NOT NULL,
    error_message        VARCHAR2(1000) NOT NULL,
    context_info         VARCHAR2(1000),
    created_at           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX ix_leave_requests_emp_dates ON leave_requests (employee_id, start_date, end_date);
CREATE INDEX ix_leave_requests_status ON leave_requests (status);
CREATE INDEX ix_leave_balances_emp_year ON leave_balances (employee_id, balance_year);
CREATE INDEX ix_leave_approvals_request ON leave_approvals (request_id, approval_level);
